### ISSUE TITLE
CSV export failed

### ISSUE THREAD

**Issue by torutk** [torutk/redmine_glossary#4]
In glossary page, click link for csv export, then error occurred.
Redmine 3.1.0 with glossary plugin only.

NameError in GlossaryController#index
uninitialized constant GlossaryPortHelper::FCSV

```
plugins/redmine_glossary/app/helpers/glossary_port_helper.rb:18:in `glossary_to_csv'
plugins/redmine_glossary/app/controllers/glossary_controller.rb:48:in `block (2 levels) in index'
vendor/bundler/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `call'
vendor/bundler/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
plugins/redmine_glossary/app/controllers/glossary_controller.rb:43:in `index'
vendor/bundler/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  :
```

**Comment by torutk** [comment]
same error found in another plugin.

https://github.com/arkhitech/redmine_timesheet_plugin/issues/58

**Comment by torutk** [comment]
try to modify init.rb to be add as following.

'''
require 'csv'
FCSV = CSV
'''
